# Generated by Django 4.0.1 on 2022-02-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Главная фотография')),
                ('additional_photo_01', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 1')),
                ('additional_photo_02', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 2')),
                ('additional_photo_03', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 3')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=30)),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.photo', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
