# Generated by Django 4.0.1 on 2022-02-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_photo_name_product_alter_product_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='AtributsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.atribut')),
            ],
        ),
        migrations.CreateModel(
            name='AtributValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('atribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.atribut')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название раздела')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photo_01',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photo_02',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_photo_03',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Доп фото 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(default='cascade', upload_to='photos/%Y/%m/%d', verbose_name='Главная фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='atributvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='atributsgroup',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.section', verbose_name='Раздел'),
        ),
    ]
